version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - gradle test
  post_build:
    commands:
      - echo Build completed on `date`
      - gradle package
artifacts:
  files:
    - target/application.jar
    - appspec.yml
  discard-paths: yes